### ISSUE TITLE
"go build" & "go run" creating work/tmp directory permission denied

### ISSUE THREAD

**Issue by jwanhs** [Gurkengewuerz/SSHContainer#1]
Beim Ausführen von Go-Programmen (in workspace Ordner) mit go run und go build tritt ein Fehler auf:

```shell
$ go run test.go                 
go: creating work dir: mkdir /tmp/go-build766958139: permission denied
$ go build -o test_binary test.go
go: creating work dir: mkdir /tmp/go-build1165311646: permission denied
$ pwd
/workspace
```

"test.go"* beinhaltet:
```go
package main

import "fmt"

func main() {
    fmt.Println("hello world")
}
``` 

*[https://gobexample.com/hello-world](url)

Testverfahren:
```shell
$ echo 'package main; import "fmt"; func main() { fmt.Println("Hello from Go") }' > test.go
$ go run test.go; go build -o test_binary test.go
```

Möglicher Workaround:
```shell
[green]~ ⌚ [red]17:26:30
$ export GOTMPDIR=/workspace/tmp

[green]~ ⌚ [red]17:28:53
$ go run test.go                                   
Hello from Go

[green]~ ⌚ [red]17:29:10
$ go build -o test_binary test.go
```
(P.S. Systemzeit ist eine Stünde verspätet, Locale anpassen?)
Würde eine neue /tmp Ordner in /workspace für Benutzern Temporäredateien erstellen, und (denke) in /workspace/.profile Configdatei, `export GOTMPDIR=/workspace/tmp` hinzufügen.

✅ Python & Node prima:
```shell
~ ⌚ 16:59:35
$ echo 'print("Hello from Python")' > test.py

[green]~ ⌚ [red]16:59:36
$ python3 test.py
Hello from Python

~ ⌚ 16:59:46
$ echo 'console.log("Hello from Node.js");' > test.js

[green]~ ⌚ [red]16:59:47
$ node test.js
Hello from Node.js
```

- [x] Erkunden Sie die Umgebung (installiert sind neovim, python3, node, go)

**Comment by Gurkengewuerz** [comment]
Danke für das Feedback.

Behoben mit 3b7ba7ae47ebf33e7b47a023f6c41e380c5ed596 und 7240d0745173abbe7c89d40fe7ba8ebaf81ff9ab
